// console.log("Hello, World!");
// console.log("anish raJ");
// console.log("raJput");
// first_name = "anish raJ";
// age =19;
// console.log(first_name);
// console.log(age);
// isFollow = true;
// const student ={
//     Name : "anish",
//     age : 19,
//     cgpa :8.86,
//     idPass : true,
// };
// console.log(student);

// student.age = student.age + 1;
// student.Name = "raputana";
// console.log(student.age);
// console.log(student);


//         const product ={
//         Name : "parker pen",
//         rating : 5,
//         offer : 6,
//         price : 500,
//         isDeal : true,
//         };
//         console.log(product);


//                 const profile ={
//                     profilePic : "Jpg/png",
//                     userName : "anish raJ",
//                     post : 150,
//                     follower : "1M",
//                     following : 6,
//                     nickName : "anish",
//                     Link : "google.com",
//                     Bio : "hello world",
//                 };
//                 console.log(profile);

//                 //operator
                
//                 let a = 5;
//                 let b = 2;
//                 console.log("a = ",a);
//                 console.log("b = ",b);
//                 console.log("a+b = ",a+b);
//                 console.log("a-b = ",a-b);
//                 console.log("a*b = ",a*b);
//                 console.log("a/b = ",a/b);
//                 console.log("a%b = ",a%b);
//                 console.log("a**b = ",a**b);
                
//                 // console.log("++a = ", ++a);
//                 console.log("a++ = ", a++);
//                 console.log("a++ = ",a);
                    a=5;
                    console.log("--a =" , --a);
                    console.log("a-- = ",a--); 